package org.briansimulator.briandroid.Simulations;

import android.os.AsyncTask;
import android.util.Log;
import android.widget.TextView;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

/**
 * Created by achilleas on 31/07/13.
 *
 * The SimRunner class handles running of standalone simulations generated by
 * the Brian2 codegen module.
 */
public class SimRunner extends AsyncTask<Void, String, Void> {
    final static String LOGID = "org.briansimulator.briandroid.Simulations.SimRunner";
    protected TextView progressText;
    Class simClass;

    public void setSimClass(Class cl) {
        simClass = cl;
    }

    protected Void doInBackground(Void... _) {
        Method simSetup, simRun;
        try {
            simSetup = simClass.getDeclaredMethod("setup", (Class)null);
        } catch (NoSuchMethodException nsme) {
            Log.d(LOGID, "Class "+simClass.getName()+" does not declare setup() method.");
            nsme.printStackTrace();
            return null;
        }
        try {
            simRun = simClass.getDeclaredMethod("run", (Class)null);
        } catch (NoSuchMethodException nsme) {
            Log.d(LOGID, "Class "+simClass.getName()+" does not declare run() method.");
            nsme.printStackTrace();
            return null;
        }
        try {
            simSetup.invoke(simClass, (Object)null);
            simRun.invoke(simClass, (Object)null);
        } catch (Exception e) {  // TODO: Catch exceptions properly
            Log.d(LOGID, "Error running simulation "+simClass.getName()+". Exception trace follows.");
            e.printStackTrace();
        }
        return null;
    }

    public void setProgressView(TextView tv) {
        progressText = tv;
    }

    @Override
    protected void onProgressUpdate(String... progress) {
        progressText.setText(progress[0]);
    }
}
