import java.io.File;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;


/** Created by achilleas on 2013-08-09
 *
 * Template for simulations generated by Brian's codegen module for use
 * in BrianDROID.
 *
 * Requirements:
 *      TODO: List required methods and fields
 *
 */
public class SIMNAME {

    // these vars should be available for almost all simulations
    final static Random rng = new Random();
    final float _duration = 0.5f;
    final float dt = 0.0001f;
    float t;
    float progress;
    private String simulationStatus;
    private final String DESCRIPTION = "%%DESCRIPTION%%";

    public float getTime() {
        return t;
    }

    public float getDuration() {
        return _duration;
    }

    public float getProgress() {
        return progress;
    }


    public String getStatusText() {
        return simulationStatus;
    }

    public String getDescription() {
        return DESCRIPTION;
    }

    protected void setStatusText(String statusText) {
        simulationStatus = statusText;
    }

    protected void appendStatusText(String extraText) {
        simulationStatus += extraText;
    }

//    %%GLOBALS%%
//
//    public void setup() {
//        %%INITIALISERS%%
//    }
//
//    public void run() {
//        for (t=0; t<_duration; t+=dt) {
//            %%RUNCODE%%
//            progress = t/_duration;
//        }
//    }

}


